### ISSUE TITLE
itaigi DNS suá轉來臺灣

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/itaigi#35]
## 變更原因
按算 kā [itaigi.tw](http://itaigi.tw/) suá 轉來 臺灣dns供應商 補夢網

## 變更時間
2023.4.28～2023.5.29

## 需求
是按呢，當初時 [itaigi.tw](http://itaigi.tw/) 是 tī enom 註冊--ê，whois 是唐鳳ê名，所有權是唐鳳ê，

管理權當初時唐鳳交接hōo Johnny，Johnny koh交接hōo意傳huānn。
![圖片](https://user-images.githubusercontent.com/5996555/234772351-36c3692e-8cea-485b-8ab1-d23bbe8e08ca.png)

最近按算 [itaigi.tw](http://itaigi.tw/) tuì enom suá 轉來 臺灣dns供應商 補夢網，是考慮：

1. enom是國外公司，意傳la̍p-tsînn，愛去國稅局辦海外扣繳，造成行政負擔。
2. DNS供應商suá轉來臺灣，減少使用者連線ê attack surface，親像海底電纜斷--去……。
3. 支持臺灣服務商。
4. enom介面花花，oh用。

會選補夢網DNS，是考慮：

1. 補夢網有ISO 27001。
2. 補夢網登入有2FA。

### 機密

DNS無機密問題。補夢網kah enom登入攏有2FA。

### 完整

Cloudflare DNS已經有備份--ah。

### 可用

DNS供應商suá轉來臺灣，減少未來使用者連線ê attack surface，親像海底電纜斷--去……。
Suá供應商ê時，補夢網有講「網域轉移期間無法修改DNS和whois資訊記錄」，所以連線應該會正常。

## 解決做法Github連結

1. 去enom設定網址授權mài auto-renew
2. 寫批hōo唐鳳，報伊知。
3. 去補夢網thinn資料。

## 未來規劃

Bô。

### 審查意見

**Comment by a8568730** [comment]
## 審查意見

了解。
