### ISSUE TITLE
Kā `itaigi-leku` kah `itaigi-miasenn` 服務對 pabuy.ithuan.tw suá到 diong.ithuan.tw

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/itaigi#36]
## 需求
因為pabuy.ithuan.tw想欲關起來，服務集中，主機較好huānn。
Kā `itaigi-leku` kah `itaigi-miasenn` 服務對 pabuy.ithuan.tw suá到 diong.ithuan.tw，而且[docker-compose.yml](https://github.com/i3thuan5/itaigi-MiaSenn/blob/master/docker-compose.yml)整合入 itaigi 專案。

## 變更時間
2023.5.12～2023.5.31

## 做法
- `itaigi-leku` kah `itaigi-miasenn`整合入 itaigi 專案docker-compose.yml，嘛kā相關服務khioh做伙。
- `itaigi-leku` kah `itaigi-miasenn` 用 dockerhub 管理。

### 機密

Bô。

### 完整

Bô完整性問題。

### 可用

1. 會先用 ithoan.tw 來試，試ê時陣袂影響tio̍h線頂服務
2. Suá服務ê時，會停2點鐘。

## 解決做法Github連結

Ah-bē好。

## 未來規劃

Bô。

**Comment by a8568730** [comment]
## 審查意見

好。
