### ISSUE TITLE
文案改hōo透

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/itaigi#52]
![圖片](https://github.com/i3thuan5/itaigi/assets/5996555/910e3f38-d13a-4b7d-8882-4fad9b8a2eb9)
![圖片](https://github.com/i3thuan5/itaigi/assets/5996555/475e93f1-2bfa-40c3-97aa-2dcbc2b93f93)

**Comment by a8568730** [comment]
已經處理好勢。
