### ISSUE TITLE
變更管理：itaigi DNS record 自 cloudflare 搬來捕夢網

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/itaigi#58]
## 需求

減少風險：

- 減服務商數量，減Cloudflare。
- 減國外連線，減Cloudflare。

新架構：
![圖片](https://github.com/i3thuan5/itaigi/assets/5996555/51a1c12c-fa84-4e10-b54e-0d5c58b1a778)

本底架構：
![圖片](https://github.com/i3thuan5/itaigi/assets/5996555/d27bdca4-1608-46cf-bc5b-db3a475bb621)

## 變更時間
2024.3.28

## 做法

- DNS record 自 cloudflare 搬來捕夢網

## 影響

對咱服務ê機密、完整、可用3方面ê影響分析：

### 機密

無。

### 完整

無。

### 可用

捕夢網DNS record，ài用ka-tī用指令備份。

## 解決做法Github連結

攏是網頁設定，bē改tio̍h咱程式。若核准，明仔載3.28做伙設定。

## 未來規劃

Bô。

**Comment by a8568730** [comment]
Cloudfalre? Cloudflare?

**Comment by sih4sing5hong5** [comment]
> 了解，tsiânn清楚，多謝。 我等解決做法Github連結。 :)

攏是網頁設定，bē改tio̍h咱程式。

**Comment by a8568730** [comment]
？ 頂懸寫「Ah-bē好。」

**Comment by a8568730** [comment]
我等網頁設定好勢～

**Comment by sih4sing5hong5** [comment]
https://github.com/i3thuan5/DNS/commit/8b0d1d606539bd13f014217c8873767a15181328

![圖片](https://github.com/i3thuan5/itaigi/assets/5996555/1788c4b2-f2f0-46d1-991f-7fe11170a768)

**Comment by a8568730** [comment]
## 審查意見

辛苦！
